### ISSUE TITLE
Allow add any telegram nickname to account

### ISSUE THREAD

**Issue by LetikGit** [disintar/.github#13]
### Bug Type

Functional

### Reproduction steps

1. Go to profile settings
2. Login with telegram
3. Click "Disconnect from telegram"
4. Repeat request from step 2 to /api/bind_telegram

### Actual result

You can add any telegram nickname to profile
https://beta.disintar.io/profile/EQAyydOEBX_MQd-xyrDg9Aoxan7uS5eVS75XXxSoU6sAaH7B

### Expected result

Check if account belongs to the user

### Suggested Severity

Critical

### Device

OS: macOS
Browser chrome
Version 105

**Comment by LetikGit** [comment]
@tvorogme Looks like critical severity, additional info I sent to DM @disintarsupport

**Comment by tvorogme** [comment]
Thanks, will look into it.

**Comment by acadabus** [comment]
Thanks for report, fixed
