### ISSUE TITLE
Different grid type, lost search section. 

### ISSUE THREAD

**Issue by DenisMatveevTon** [disintar/.github#16]
### Bug Type

UX

### Reproduction steps

1. Open NFT in collection, example: [Nicola Tesla](https://beta.disintar.io/object/EQC_DXMHe2zhzksyn3wGMa6t6hL6l4un4VYa85clAAVVjM-D?filters=%5B%7B%22name%22%3A%22attributes%22%2C%22value%22%3A%5B%7B%22name%22%3A%22Theme%22%2C%22values%22%3A%5B%22Nicola%20Tesla%22%5D%7D%5D%7D%5D);
2. Follow below and tap on grid for making grid 5x5;
3. Tap on the button «Attributes» and choose few check boxes;
4. Tap on the button «Group».  

### Actual result

1. Grid changes from 5x5 to 3x3;
2. Not available search options on the same page. 

https://user-images.githubusercontent.com/113242420/190931939-2c58ce6f-9aca-4bca-a40a-ed4e4cbddcaf.mov

### Expected result

1) Grid saves previous parameters;
2) Search engine also available after choosing attributes.

### Suggested Severity

Medium

### Device

Desktop:
- OS: macOS 12.5.1
- Browser DuckDuckGo
- Version 0.28.8

**Comment by tvorogme** [comment]
Actually, this is UX problem with group button, it did not what u think :) 

We will fix it in https://github.com/disintar/.github/issues/17
