### ISSUE TITLE
An unknown NFT has settled in my room

### ISSUE THREAD

**Issue by maxuver** [disintar/.github#24]
### Bug Type

Security

### Reproduction steps

1. Open my room: https://beta.disintar.io/profile/EQCX0M7_pQrL7e2jnVYZnXWpJzCK_Z4ryYCWU1qT9I6jdIas
2. Link for unknown NFT: https://beta.disintar.io/profile/EQAyydOEBX_MQd-xyrDg9Aoxan7uS5eVS75XXxSoU6sAaH7B

https://user-images.githubusercontent.com/78837452/191411503-608b420a-5301-4e6a-9399-eaed6633ab16.mp4

### Actual result

From the user's point of view, this is an inexplicable scenario.

### Expected result

Room owners should remain calm and make sure that no one illegally gets to their digital property.

### Suggested Severity

Vulnerability

### Device

OS: Windows 10
Browser: Chrome
Version: 105.0.5195.127 (Official Build) (64-bit)

**Comment by tvorogme** [comment]
Thanks! this is part of https://github.com/disintar/.github/issues/8

Soon will be fixed
