### ISSUE TITLE
Fail to detect NFTs

### ISSUE THREAD

**Issue by zmxv** [disintar/.github#3]
### Bug Type

Functional

### Reproduction steps

1. Visit https://disintar.io/
2. Scan the QR code to connect to Tonkeeper
3. Switch to the "Owned" tab on the profile page

### Actual result

<img width="980" alt="Screen Shot 2022-09-17 at 12 50 24 AM" src="https://user-images.githubusercontent.com/363061/190689848-71d455e9-c8c4-4f1e-92f2-f37718267e91.png">

### Expected result

Existing NFTs including .ton domains should be detected and displayed.

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: macOS
- Browser: Chrome
- Version: 105

Smartphone (please complete the following information):
- Device: iPhone 13 Pro
- OS: iOS 15.6.1
- Browser: Mobile Safari
- Version: Tonkeeper 2.6

**Comment by Reveloper** [comment]
Wanted to post this issue, but I'm late.

Little addition for disintar team:
The expected result according to the rules users see in the  [Disintar_instruction](https://beta.disintar.io/static_disintar/DISINTAR_instruction.pdf), where we can't see any information about exceptions for NFT viewer:
![image](https://user-images.githubusercontent.com/39581753/190849617-476a57c1-0101-4348-836f-42ad423d07b1.png)

**Comment by tvorogme** [comment]
This is part of the big problem and theme of the next Disinter update, which we have been preparing for several months. As soon as we are ready to roll out the updates owner NFT will be updated instantly.
