### ISSUE TITLE
The Room section doesn't refresh after signing in and picking the current account.

### ISSUE THREAD

**Issue by Reveloper** [disintar/.github#8]
### Bug Type

UI

### Reproduction steps

1. Open any Room page without authorization.
![image](https://user-images.githubusercontent.com/39581753/190850830-6e303294-e175-4de7-a0c4-36b6a93d36d5.png)
3. Sign in.
4. Click on your authorized account(top right corner icon).

### Actual result

Owned, Created NFTs, Created Collections sections display data for a chosen account, but the Room section still displays data from the previous Room.
![image](https://user-images.githubusercontent.com/39581753/190850859-173e818b-8ea3-404f-a27e-e5bf73631112.png)

### Expected result

The room section should display data for the chosen account.
![image](https://user-images.githubusercontent.com/39581753/190850948-d3cb7347-f932-4cea-981d-9cf6614fbdf0.png)

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: Windows 10 Pro
- Browser Google Chrome
- Version 105.0.5195.127

**Comment by data-will-be-here** [comment]
Also if you try to open any user's room and then click on your profile, information about likes will not be updated. Also room picture will not updated when you click 'back' or 'next' in browser

https://user-images.githubusercontent.com/85282394/190918928-229189df-58eb-45f6-8a79-90cab6068b10.mp4
