### ISSUE TITLE
The information is not updated after purchase

### ISSUE THREAD

**Issue by data-will-be-here** [disintar/.github#9]
### Bug Type

UI

### Reproduction steps

When a user bought an NFT and the owner in the blockchain changed, for some reason the information on the site is not updated for some time yet.

### Actual result

The user sees as if the NFT still belongs to him, and the buyer does not see the purchased NFT. 
>30 minutes have passed between the time of purchase and the publication of this report, and the information has not been updated. In the blockchain everything is ok.

### Expected result

The NFT should be immediately transferred to the new owner without a delay of 5-10-30 minutes, even though it is only an interface error.

### Suggested Severity

Low

### Device

- any

### Additional Context

![image](https://user-images.githubusercontent.com/85282394/190854759-26912aae-422b-4996-8757-ba18d8ffd27c.png)
![image](https://user-images.githubusercontent.com/85282394/190854775-ae2aa994-392c-4c00-bdb4-bcd1393c7e9e.png)

proof that the sale-contract finished its working
![image](https://user-images.githubusercontent.com/85282394/190855161-8baf67e1-acf3-4a11-8d21-bacfd3a1b0a4.png)

**Comment by tvorogme** [comment]
This is part of the big problem and theme of the next Disinter update, which we have been preparing for several months. As soon as we are ready to roll out the updates owner NFT will be updated instantly.
